Repository falcosecurity/plugin-sdk-go, pull requests merged in 2021-09, with the labels that each got.

#4 docs(README.md): notice regarding the project status
  README.md
Labels: dco-signoff: yes, approved, lgtm, size/XS

#7 plugin_next_batch should return success when batch < max batch size
  wrappers/wrappers.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/XS, area/plugin-sdk, release-note

#8 Note that event numbers are filled in by the plugin framework.
  sdk.go
Labels: dco-signoff: yes, approved, lgtm, size/XS, area/plugin-sdk, kind/cleanup, release-note

#6 fix(wrappers): properly reverse if check in async extractor
  wrappers/wrappers.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, area/plugin-sdk, release-note, size/S, ok-to-test
